import uuid
from datetime import datetime
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from app.core.fields import Name, optional_text

BARCODE_PATTERN = r"^(\d{8}|\d{12,14})$"

Barcode = optional_text(14, pattern=BARCODE_PATTERN)
Per100g = Annotated[
    Annotated[float, Field(ge=0, le=100, allow_inf_nan=False)] | None,
    Field(description="Grams per 100 g"),
]
Visibility = Literal["private", "catalog_pending", "catalog_rejected", "catalog"]


class FoodIn(BaseModel):
    name: Name
    brand: optional_text(100) = None
    barcode: Barcode = Field(default=None, description="EAN-8, UPC-A, EAN-13 or GTIN-14")
    kcal_per_100g: float = Field(ge=0, le=900, allow_inf_nan=False)
    protein_g: Per100g = None
    carbs_g: Per100g = None
    fat_g: Per100g = None
    sugar_g: Per100g = None
    salt_g: Per100g = None
    serving_size_g: float | None = Field(default=None, gt=0, le=5000, allow_inf_nan=False)

    @model_validator(mode="after")
    def _nutrients_are_plausible(self):
        if self.sugar_g is not None and self.carbs_g is not None and self.sugar_g > self.carbs_g:
            raise ValueError("sugar_g cannot be larger than carbs_g")
        macros = (self.protein_g or 0) + (self.carbs_g or 0) + (self.fat_g or 0)
        if macros > 100.5:
            raise ValueError("protein_g, carbs_g and fat_g cannot add up to more than 100 g")
        return self


class FoodCreate(FoodIn):
    id: uuid.UUID | None = Field(default=None, description="Optional id generated by the client")
    catalog_id: uuid.UUID | None = Field(
        default=None,
        description="Catalog entry this private copy (e.g. with own corrections) is based on",
    )


class FoodOut(BaseModel):
    """Never contains the owner or the proposing user."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    catalog_id: uuid.UUID | None
    name: str
    brand: str | None
    barcode: str | None
    kcal_per_100g: float | None
    protein_g: float | None
    carbs_g: float | None
    fat_g: float | None
    sugar_g: float | None
    salt_g: float | None
    serving_size_g: float | None
    image_url: str | None
    source: Literal["openfoodfacts", "custom"] = Field(
        description="openfoodfacts: data from Open Food Facts (ODbL), the source must be named"
    )
    source_synced_at: datetime | None
    visibility: Visibility
    created_at: datetime
    updated_at: datetime


class CatalogFoodPatch(BaseModel):
    """Moderation: decide on a proposal and optionally correct its data."""

    visibility: Literal["catalog_pending", "catalog_rejected", "catalog"] | None = None
    name: Name | None = None
    brand: optional_text(100) = None
    barcode: Barcode = None
    kcal_per_100g: float | None = None
    protein_g: float | None = None
    carbs_g: float | None = None
    fat_g: float | None = None
    sugar_g: float | None = None
    salt_g: float | None = None
    serving_size_g: float | None = None
