import uuid
from datetime import date, datetime
from typing import Annotated, Literal

from pydantic import (
    AfterValidator,
    BaseModel,
    ConfigDict,
    Field,
    StringConstraints,
    model_validator,
)

from app.core.fields import Name
from app.core.fields import optional_text as _optional_text

TypeName = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=80)]
Brand = _optional_text(100)
LongText = _optional_text(5000)
WebsiteUrl = _optional_text(500, pattern=r"^https?://\S+$")
WeightG = Annotated[Annotated[int, Field(ge=0, le=1_000_000)] | None, Field()]


MAX_PRICE = 1_000_000


def _check_price(value: float) -> float:
    if abs(value * 100 - round(value * 100)) > 1e-6:
        raise ValueError("price must not have more than two decimal places")
    return round(value, 2)


Price = Annotated[
    Annotated[float, Field(ge=0, le=MAX_PRICE, allow_inf_nan=False), AfterValidator(_check_price)]
    | None,
    Field(description="Purchase price as a number with at most two decimal places"),
]


# --- Types ---


class GearTypeIn(BaseModel):
    name: TypeName
    sort_order: int = Field(default=0, ge=0, le=100_000)


class GearTypeCreate(GearTypeIn):
    standard: bool = Field(
        default=False, description="Add to the standard list for all users (admin only)"
    )


class GearTypeOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    name: str
    sort_order: int
    standard: bool


# --- Tags ---


class GearTagIn(BaseModel):
    name: Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=50)]
    color: Annotated[str, StringConstraints(pattern=r"^#[0-9a-fA-F]{6}$")] | None = Field(
        default=None, description="Display colour as #RRGGBB"
    )


class GearTagCreate(GearTagIn):
    id: uuid.UUID | None = Field(default=None, description="Optional id generated by the client")


class GearTagOut(GearTagIn):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID


# --- Items ---


class GearItemIn(BaseModel):
    name: Name
    brand: Brand = None
    type_id: uuid.UUID | None = None
    weight_g: WeightG = None
    purchase_date: date | None = None
    purchase_price: Price = None
    currency: str | None = Field(
        default=None, pattern=r"^[A-Z]{3}$", description="ISO 4217; required with a price"
    )
    description: LongText = None
    notes: LongText = None
    website_url: WebsiteUrl = None
    status: Literal["active", "retired"] = "active"
    serial_number: _optional_text(100) = None
    size: _optional_text(50) = None
    color: _optional_text(50) = None
    tag_ids: list[uuid.UUID] = Field(default_factory=list, max_length=50)

    @model_validator(mode="after")
    def _price_needs_currency(self):
        if self.purchase_price is not None and self.currency is None:
            raise ValueError("currency is required when purchase_price is set")
        return self


class GearItemCreate(GearItemIn):
    id: uuid.UUID | None = Field(default=None, description="Optional id generated by the client")
    catalog_id: uuid.UUID | None = Field(
        default=None,
        description="Approved catalog entry used as template; its image is copied to the item",
    )


class GearItemOut(GearItemIn):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    catalog_id: uuid.UUID | None
    image_file_id: uuid.UUID | None = Field(
        description="Changes with every new image; load it from /gear/items/{id}/image"
    )
    created_at: datetime
    updated_at: datetime


# --- Summary ---


class MoneyTotal(BaseModel):
    currency: str
    amount: float


class GearTotals(BaseModel):
    item_count: int
    weight_g: int = Field(description="Sum of the weights of all items that have one")
    items_without_weight: int
    value: list[MoneyTotal] = Field(description="Sum of the purchase prices, per currency")
    items_without_price: int


class GearSummaryGroup(GearTotals):
    key: str | None = Field(description="Id or value of the group; null = not assigned")
    label: str | None


class GearSummaryOut(BaseModel):
    group_by: Literal["type", "tag", "status", "brand"] | None
    total: GearTotals
    groups: list[GearSummaryGroup]


# --- Packing lists ---


class GearListEntry(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    gear_item_id: uuid.UUID
    quantity: int = Field(default=1, ge=1, le=999)


class GearListIn(BaseModel):
    name: Name
    description: LongText = None
    entries: list[GearListEntry] = Field(default_factory=list, max_length=500)


class GearListCreate(GearListIn):
    id: uuid.UUID | None = Field(default=None, description="Optional id generated by the client")


class GearListOut(BaseModel):
    id: uuid.UUID
    name: str
    description: str | None
    entries: list[GearListEntry]
    total_weight_g: int = Field(description="Sum of weight × quantity of all entries with a weight")
    created_at: datetime
    updated_at: datetime


# --- Catalog ---


class CatalogItemOut(BaseModel):
    """Product data only; never contains personal fields or the proposing user."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    name: str
    brand: str | None
    type_id: uuid.UUID | None
    nominal_weight_g: int | None
    website_url: str | None
    image_file_id: uuid.UUID | None
    status: Literal["pending", "approved", "rejected"]


class CatalogItemPatch(BaseModel):
    """Moderation: decide on a proposal and optionally correct its product data."""

    status: Literal["pending", "approved", "rejected"] | None = None
    name: Name | None = None
    brand: Brand = None
    type_id: uuid.UUID | None = None
    nominal_weight_g: WeightG = None
    website_url: WebsiteUrl = None
