import uuid
from datetime import date, datetime
from decimal import Decimal
from typing import Annotated, Literal

from pydantic import BaseModel, BeforeValidator, ConfigDict, Field, StringConstraints


def _blank_to_none(value):
    if isinstance(value, str):
        return value.strip() or None
    return value


def _optional_text(max_length: int):
    text = Annotated[str, StringConstraints(max_length=max_length)]
    return Annotated[text | None, BeforeValidator(_blank_to_none)]


Name = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=200)]
TypeName = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=80)]
Brand = _optional_text(100)
LongText = _optional_text(5000)
WebsiteUrl = Annotated[
    Annotated[str, StringConstraints(max_length=500, pattern=r"^https?://\S+$")] | None,
    BeforeValidator(_blank_to_none),
]
WeightG = Annotated[Annotated[int, Field(ge=0, le=1_000_000)] | None, Field()]


# --- Types ---


class GearTypeIn(BaseModel):
    name: TypeName
    sort_order: int = Field(default=0, ge=0, le=100_000)


class GearTypeCreate(GearTypeIn):
    standard: bool = Field(
        default=False, description="Add to the standard list for all users (admin only)"
    )


class GearTypeOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    name: str
    sort_order: int
    standard: bool


# --- Items ---


class GearItemIn(BaseModel):
    name: Name
    brand: Brand = None
    type_id: uuid.UUID | None = None
    weight_g: WeightG = None
    purchase_date: date | None = None
    purchase_price: Decimal | None = Field(default=None, ge=0, max_digits=10, decimal_places=2)
    currency: str | None = Field(default=None, pattern=r"^[A-Z]{3}$", description="ISO 4217")
    description: LongText = None
    notes: LongText = None
    website_url: WebsiteUrl = None
    status: Literal["active", "retired"] = "active"
    serial_number: _optional_text(100) = None
    size: _optional_text(50) = None
    color: _optional_text(50) = None


class GearItemCreate(GearItemIn):
    id: uuid.UUID | None = Field(default=None, description="Optional id generated by the client")
    catalog_id: uuid.UUID | None = Field(
        default=None,
        description="Approved catalog entry used as template; its image is copied to the item",
    )


class GearItemOut(GearItemIn):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    catalog_id: uuid.UUID | None
    image_file_id: uuid.UUID | None = Field(
        description="Changes with every new image; load it from /gear/items/{id}/image"
    )
    created_at: datetime
    updated_at: datetime


# --- Packing lists ---


class GearListEntry(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    gear_item_id: uuid.UUID
    quantity: int = Field(default=1, ge=1, le=999)


class GearListIn(BaseModel):
    name: Name
    description: LongText = None
    entries: list[GearListEntry] = Field(default_factory=list, max_length=500)


class GearListCreate(GearListIn):
    id: uuid.UUID | None = Field(default=None, description="Optional id generated by the client")


class GearListOut(BaseModel):
    id: uuid.UUID
    name: str
    description: str | None
    entries: list[GearListEntry]
    total_weight_g: int = Field(description="Sum of weight × quantity of all entries with a weight")
    created_at: datetime
    updated_at: datetime


# --- Catalog ---


class CatalogItemOut(BaseModel):
    """Product data only; never contains personal fields or the proposing user."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    name: str
    brand: str | None
    type_id: uuid.UUID | None
    nominal_weight_g: int | None
    website_url: str | None
    image_file_id: uuid.UUID | None
    status: Literal["pending", "approved", "rejected"]


class CatalogItemPatch(BaseModel):
    """Moderation: decide on a proposal and optionally correct its product data."""

    status: Literal["pending", "approved", "rejected"] | None = None
    name: Name | None = None
    brand: Brand = None
    type_id: uuid.UUID | None = None
    nominal_weight_g: WeightG = None
    website_url: WebsiteUrl = None
