import uuid
from datetime import datetime
from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, model_validator

from app.core.fields import Name, optional_text

EntryId = Annotated[
    uuid.UUID | None,
    Field(description="Id of an existing entry, or an optional client-generated id for a new one"),
]
Latitude = Annotated[float, Field(ge=-90, le=90, allow_inf_nan=False)]
Longitude = Annotated[float, Field(ge=-180, le=180, allow_inf_nan=False)]


# --- Lists inside the tour document ---


class TourGearIn(BaseModel):
    id: EntryId = None
    gear_item_id: uuid.UUID | None = Field(
        default=None, description="Required for a new entry; must be a gear item of the caller"
    )
    quantity: int = Field(default=1, ge=1, le=999)
    carried: bool = Field(default=True, description="Counts towards the pack weight")


class TourGearOut(BaseModel):
    id: uuid.UUID
    gear_item_id: uuid.UUID | None
    name: str
    brand: str | None
    weight_g: int | None = Field(description="Weight of one piece when it was added (snapshot)")
    quantity: int
    carried: bool


class TourFoodIn(BaseModel):
    id: EntryId = None
    food_item_id: uuid.UUID | None = Field(
        default=None, description="Required for a new entry; own food or one from the catalog"
    )
    amount_g: float = Field(gt=0, le=100_000, allow_inf_nan=False)
    carried: bool = Field(default=True, description="Counts towards the pack weight")
    eaten: bool = Field(default=False, description="Counts towards the calories eaten")
    eaten_at: AwareDatetime | None = None


class TourFoodOut(BaseModel):
    id: uuid.UUID
    food_item_id: uuid.UUID | None
    name: str
    kcal_per_100g: float | None = Field(description="Value when the entry was added (snapshot)")
    amount_g: float
    kcal: float | None
    carried: bool
    eaten: bool
    eaten_at: datetime | None


class TourPeakIn(BaseModel):
    id: EntryId = None
    name: Name
    elevation_m: int | None = Field(default=None, ge=-500, le=9000)
    lat: Latitude | None = None
    lon: Longitude | None = None
    reached_at: AwareDatetime | None = None

    @model_validator(mode="after")
    def _position_is_complete(self):
        if (self.lat is None) != (self.lon is None):
            raise ValueError("lat and lon must be given together")
        return self


class TourPeakOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    name: str
    elevation_m: int | None
    lat: float | None
    lon: float | None
    reached_at: datetime | None


# --- Tour ---


class TourIn(BaseModel):
    """The editable tour document. PUT replaces it as a whole, including the lists."""

    title: Name
    summary: optional_text(20_000) = None
    start_time: AwareDatetime | None = None
    end_time: AwareDatetime | None = None
    duration_minutes: int | None = Field(
        default=None, ge=0, le=100_000, description="Manual value; null = computed from the times"
    )
    pack_weight_start_g: int | None = Field(
        default=None, ge=0, le=200_000, description="Manual value; null = computed from the lists"
    )
    calories_burned: float | None = Field(
        default=None, ge=0, le=50_000, allow_inf_nan=False, description="Manual value"
    )
    gear: list[TourGearIn] = Field(default_factory=list, max_length=500)
    food: list[TourFoodIn] = Field(default_factory=list, max_length=500)
    peaks: list[TourPeakIn] = Field(default_factory=list, max_length=100)

    @model_validator(mode="after")
    def _end_is_not_before_start(self):
        if self.start_time and self.end_time and self.end_time < self.start_time:
            raise ValueError("end_time must not be before start_time")
        return self


class TourCreate(TourIn):
    id: uuid.UUID | None = Field(default=None, description="Optional id generated by the client")


class TourOwner(BaseModel):
    id: uuid.UUID
    display_name: str | None


class GeoPoint(BaseModel):
    lat: float
    lon: float
    name: str | None


class TourComputed(BaseModel):
    """Values derived by the server; used wherever the manual value is empty."""

    duration_minutes: int | None = Field(description="From start_time and end_time")
    pack_weight_start_g: int = Field(description="Carried gear plus carried food")
    calories_eaten: float = Field(description="Sum of the eaten food entries")


class TourBase(BaseModel):
    id: uuid.UUID
    owner: TourOwner
    permission: Literal["owner", "edit", "read"] = Field(description="Access of the caller")
    title: str
    start_time: datetime | None
    end_time: datetime | None
    cover_photo_id: uuid.UUID | None
    version: int
    created_at: datetime
    updated_at: datetime


class TourListItem(TourBase):
    peaks: list[str] = Field(description="Names of the peaks")


class TourOut(TourBase):
    summary: str | None
    duration_minutes: int | None
    pack_weight_start_g: int | None
    calories_burned: float | None
    calories_burned_source: Literal["manual", "estimated"] | None
    computed: TourComputed
    start_point: GeoPoint | None
    end_point: GeoPoint | None
    points_source: Literal["gpx", "manual"] | None
    track_source: Literal["device", "drawn", "none"]
    gear: list[TourGearOut]
    food: list[TourFoodOut]
    peaks: list[TourPeakOut]


# --- Waypoints ---


class WaypointIn(BaseModel):
    id: uuid.UUID | None = Field(default=None, description="Optional id generated by the client")
    name: Name
    description: optional_text(5000) = None
    icon: optional_text(50) = None
    lat: Latitude
    lon: Longitude
    elevation_m: float | None = Field(default=None, ge=-500, le=9000, allow_inf_nan=False)


class WaypointPatch(BaseModel):
    name: Name | None = None
    description: optional_text(5000) = None
    icon: optional_text(50) = None
    lat: Latitude | None = None
    lon: Longitude | None = None
    elevation_m: float | None = Field(default=None, ge=-500, le=9000, allow_inf_nan=False)


class WaypointOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    name: str
    description: str | None
    icon: str | None
    lat: float
    lon: float
    track_distance_m: float | None
    elevation_m: float | None
