import uuid
from datetime import datetime
from typing import Annotated, Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    StringConstraints,
    computed_field,
    field_validator,
)

from app.core.fields import Name, optional_text
from app.modules.planning.estimate import PRESETS, Pace

Latitude = Annotated[float, Field(ge=-90, le=90, allow_inf_nan=False)]
Longitude = Annotated[float, Field(ge=-180, le=180, allow_inf_nan=False)]
Profile = Literal["hiking", "direct"]

MAX_WAYPOINTS = 100

Difficulty = Annotated[
    int,
    Field(
        ge=1,
        le=6,
        description="Hardest allowed path on the SAC hiking scale (1 = T1 … 6 = T6); "
        "easier paths are included, demanding ones are preferred where possible",
    ),
]


class PaceIn(BaseModel):
    """How fast the walker is. A preset brings its own values; `custom` takes them from here."""

    preset: Literal["dav", "sac", "pro", "custom"] = "dav"
    name: optional_text(100) = Field(default=None, description="Name of a saved custom pace")
    ascent_m_per_h: float = Field(default=300, ge=50, le=3000, allow_inf_nan=False)
    descent_m_per_h: float = Field(default=500, ge=50, le=5000, allow_inf_nan=False)
    distance_km_per_h: float = Field(default=4, ge=0.5, le=20, allow_inf_nan=False)

    def resolved(self) -> "PaceIn":
        """The pace with the values that count: those of the preset, or the given ones."""
        preset = PRESETS.get(self.preset)
        if preset is None:
            return self
        return PaceIn(
            preset=self.preset,
            ascent_m_per_h=preset.ascent_m_per_h,
            descent_m_per_h=preset.descent_m_per_h,
            distance_km_per_h=preset.distance_km_per_h,
        )

    def as_pace(self) -> Pace:
        pace = self.resolved()
        return Pace(pace.ascent_m_per_h, pace.descent_m_per_h, pace.distance_km_per_h)


class PaceOut(BaseModel):
    preset: str
    name: str | None
    ascent_m_per_h: float
    descent_m_per_h: float
    distance_km_per_h: float


class PaceProfileIn(BaseModel):
    name: Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=100)]
    ascent_m_per_h: float = Field(ge=50, le=3000, allow_inf_nan=False)
    descent_m_per_h: float = Field(ge=50, le=5000, allow_inf_nan=False)
    distance_km_per_h: float = Field(ge=0.5, le=20, allow_inf_nan=False)


class PaceProfileCreate(PaceProfileIn):
    id: uuid.UUID | None = Field(default=None, description="Optional id generated by the client")


class PaceProfileOut(PaceProfileIn):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    updated_at: datetime


class PathChoice(BaseModel):
    """Which paths the routing may use; without meaning for straight lines."""

    max_difficulty: Difficulty = 3
    via_ferrata: bool = Field(
        default=False, description="Via ferratas may be used; a category of their own"
    )
    pace: PaceIn = Field(default_factory=PaceIn, description="For the walking time")


class RouteWaypoint(BaseModel):
    lat: Latitude
    lon: Longitude
    name: optional_text(200) = None
    direct: bool = Field(
        default=False,
        description="The leg to this point is a straight line, whatever the profile says",
    )


Waypoints = Annotated[list[RouteWaypoint], Field(min_length=2, max_length=MAX_WAYPOINTS)]


Tag = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=40)]


class RoutePreviewIn(PathChoice):
    profile: Profile = "hiking"
    waypoints: Waypoints
    start_time: AwareDatetime | None = Field(
        default=None, description="When the walker sets out; adds `sun` to the answer"
    )


class RouteSeries(BaseModel):
    """The line of the route as columns of equal length."""

    distance_m: list[float]
    lat: list[float]
    lon: list[float]
    elevation_m: list[float | None] | None
    time_s: list[int] | None = Field(
        default=None, description="Seconds from the start at every point, for the chosen pace"
    )


class SummitOut(BaseModel):
    time: datetime
    elevation_m: float
    distance_m: float
    sun_height_deg: float = Field(description="Height of the sun above the horizon then")
    sun_direction_deg: int = Field(description="Compass direction of the sun then, 180 = south")


class SunOut(BaseModel):
    """The day of the tour at its start point; times in UTC, for the mathematical horizon."""

    dawn: datetime | None = Field(description="First light (civil twilight begins)")
    sunrise: datetime | None
    noon: datetime
    sunset: datetime | None
    dusk: datetime | None = Field(description="Last light (civil twilight ends)")
    end_time: datetime = Field(description="Start time plus walking time, without breaks")
    starts_in_dark: bool
    ends_in_dark: bool
    daylight_left_s: int | None = Field(
        description="Between the end of the tour and sunset; negative if the sun sets first"
    )
    summit: SummitOut | None = Field(description="When the highest point is reached")


class RouteStats(BaseModel):
    distance_m: float
    ascent_m: float | None
    descent_m: float | None
    min_elevation_m: float | None
    max_elevation_m: float | None
    duration_s: int = Field(description="Estimated walking time without breaks, for the pace")

    @computed_field(description="The walking time is always an estimate")
    @property
    def duration_estimated(self) -> bool:
        return True


class RoutePreviewOut(RouteStats):
    engine: str = Field(description="brouter, direct or brouter+direct")
    series: RouteSeries
    sun: SunOut | None = None


class RouteIn(PathChoice):
    title: Name
    description: optional_text(5000) = None
    tags: list[Tag] = Field(default_factory=list, max_length=20)
    start_time: AwareDatetime | None = Field(
        default=None, description="When the walker sets out; null if not decided yet"
    )
    profile: Profile = "hiking"
    waypoints: Waypoints

    @field_validator("tags")
    @classmethod
    def _unique_tags(cls, tags: list[str]) -> list[str]:
        # The same tag twice says nothing new; the first spelling stays.
        seen: dict[str, str] = {}
        for tag in tags:
            seen.setdefault(tag.casefold(), tag)
        return list(seen.values())


class RouteCreate(RouteIn):
    id: uuid.UUID | None = Field(default=None, description="Optional id generated by the client")


class RouteUpdate(RouteIn):
    version: int = Field(description="Version the change is based on; 409 if outdated")


class RouteSummary(RouteStats):
    """A route without its line, for lists."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    title: str
    description: str | None
    tags: list[str]
    start_time: datetime | None
    profile: str
    max_difficulty: int
    via_ferrata: bool
    pace: PaceOut
    engine: str
    version: int
    created_at: datetime
    updated_at: datetime


class RouteOut(RouteSummary):
    waypoints: list[RouteWaypoint]
    series: RouteSeries
    sun: SunOut | None = Field(description="Sunrise and sunset for the tour; null without start")


class SegmentInfo(BaseModel):
    """Path data of one tile of 5° x 5°, named after its south-west corner (e.g. E5_N45)."""

    name: str
    size_bytes: int
    modified: datetime


class ProfileInfo(BaseModel):
    id: str
    available: bool


class DifficultyInfo(BaseModel):
    level: int
    code: str = Field(description="T1 … T6")
    sac_scale: str = Field(description="Value of the OpenStreetMap key sac_scale")


class PacePreset(BaseModel):
    id: str
    ascent_m_per_h: float
    descent_m_per_h: float
    distance_km_per_h: float


class PlanningInfo(BaseModel):
    paces: list[PacePreset] = Field(description="The built-in paces for the walking time")
    difficulties: list[DifficultyInfo]
    routing_available: bool = Field(description="False: only straight lines can be planned")
    profiles: list[ProfileInfo]
    attribution: str | None = Field(description="Must be shown with routes along paths (ODbL)")
    max_waypoints: int
