import uuid
from datetime import date, datetime
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, computed_field

from app.core.fields import Name, optional_text

Latitude = Annotated[float, Field(ge=-90, le=90, allow_inf_nan=False)]
Longitude = Annotated[float, Field(ge=-180, le=180, allow_inf_nan=False)]
Profile = Literal["hiking", "direct"]

MAX_WAYPOINTS = 100

Difficulty = Annotated[
    int,
    Field(
        ge=1,
        le=6,
        description="Hardest allowed path on the SAC hiking scale (1 = T1 … 6 = T6); "
        "easier paths are included, demanding ones are preferred where possible",
    ),
]


class PathChoice(BaseModel):
    """Which paths the routing may use; without meaning for straight lines."""

    max_difficulty: Difficulty = 3
    via_ferrata: bool = Field(
        default=False, description="Via ferratas may be used; a category of their own"
    )


class RouteWaypoint(BaseModel):
    lat: Latitude
    lon: Longitude
    name: optional_text(200) = None
    direct: bool = Field(
        default=False,
        description="The leg to this point is a straight line, whatever the profile says",
    )


Waypoints = Annotated[list[RouteWaypoint], Field(min_length=2, max_length=MAX_WAYPOINTS)]


class RoutePreviewIn(PathChoice):
    profile: Profile = "hiking"
    waypoints: Waypoints


class RouteSeries(BaseModel):
    """The line of the route as columns of equal length."""

    distance_m: list[float]
    lat: list[float]
    lon: list[float]
    elevation_m: list[float | None] | None


class RouteStats(BaseModel):
    distance_m: float
    ascent_m: float | None
    descent_m: float | None
    min_elevation_m: float | None
    max_elevation_m: float | None
    duration_s: int = Field(description="Estimated walking time without breaks (DIN 33466)")

    @computed_field(description="The walking time is always an estimate")
    @property
    def duration_estimated(self) -> bool:
        return True


class RoutePreviewOut(RouteStats):
    engine: str = Field(description="brouter, direct or brouter+direct")
    series: RouteSeries


class RouteIn(PathChoice):
    title: Name
    description: optional_text(5000) = None
    planned_date: date | None = None
    profile: Profile = "hiking"
    waypoints: Waypoints


class RouteCreate(RouteIn):
    id: uuid.UUID | None = Field(default=None, description="Optional id generated by the client")


class RouteUpdate(RouteIn):
    version: int = Field(description="Version the change is based on; 409 if outdated")


class RouteSummary(RouteStats):
    """A route without its line, for lists."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    title: str
    description: str | None
    planned_date: date | None
    profile: str
    max_difficulty: int
    via_ferrata: bool
    engine: str
    version: int
    created_at: datetime
    updated_at: datetime


class RouteOut(RouteSummary):
    waypoints: list[RouteWaypoint]
    series: RouteSeries


class ProfileInfo(BaseModel):
    id: str
    available: bool


class DifficultyInfo(BaseModel):
    level: int
    code: str = Field(description="T1 … T6")
    sac_scale: str = Field(description="Value of the OpenStreetMap key sac_scale")


class PlanningInfo(BaseModel):
    difficulties: list[DifficultyInfo]
    routing_available: bool = Field(description="False: only straight lines can be planned")
    profiles: list[ProfileInfo]
    attribution: str | None = Field(description="Must be shown with routes along paths (ODbL)")
    max_waypoints: int
