"""All texts of the web frontend, in German. Templates and views use `t('key')`."""

TEXTS = {
    "app.title": "hiker",
    "nav.tours": "Touren",
    "nav.gear": "Ausrüstung",
    "nav.food": "Essen",
    "nav.profile": "Profil",
    "nav.logout": "Abmelden",
    "action.save": "Speichern",
    "action.delete": "Löschen",
    "action.edit": "Bearbeiten",
    "action.cancel": "Abbrechen",
    "action.search": "Suchen",
    "action.add": "Hinzufügen",
    "action.back": "Zurück",
    "common.all": "Alle",
    "common.none": "Keine",
    "common.name": "Name",
    "common.saved": "Gespeichert.",
    "common.deleted": "Gelöscht.",
    "common.confirm_delete": "Wirklich löschen?",
    # --- auth ---
    "auth.login": "Anmelden",
    "auth.register": "Konto anlegen",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.password_hint": "Mindestens 10 Zeichen",
    "auth.display_name": "Anzeigename",
    "auth.to_register": "Noch kein Konto? Konto anlegen",
    "auth.to_login": "Schon ein Konto? Anmelden",
    "auth.signed_in_as": "Angemeldet als {name}",
    "auth.admin": "Administrator",
    "profile.title": "Profil",
    "profile.intro": (
        "Diese Angaben sind freiwillig. Sie dienen nur der Schätzung des Kalorienverbrauchs "
        "und sind für niemanden sonst sichtbar."
    ),
    "profile.weight": "Gewicht (kg)",
    "profile.birth_year": "Geburtsjahr",
    "profile.sex": "Geschlecht",
    "profile.sex.none": "nicht festgelegt",
    "profile.sex.female": "weiblich",
    "profile.sex.male": "männlich",
    "profile.sex.trans": "trans",
    "profile.sex.undisclosed": "keine Angabe",
    "profile.max_heart_rate": "Maximale Herzfrequenz",
    "profile.resting_heart_rate": "Ruheherzfrequenz",
    # --- gear ---
    "gear.new": "Neuer Gegenstand",
    "gear.edit": "Gegenstand bearbeiten",
    "gear.empty": "Keine Ausrüstung gefunden.",
    "gear.search_hint": "Name oder Marke",
    "gear.summary": "Summen",
    "gear.manage": "Tags und Kategorien",
    "gear.catalog": "Katalog",
    "gear.lists": "Packlisten",
    "gear.lists_hint": "Eine Packliste lässt sich beim Bearbeiten einer Tour komplett übernehmen.",
    "gear.lists_empty": "Noch keine Packliste.",
    "gear.list_new": "Neue Packliste",
    "gear.list_edit": "Packliste bearbeiten",
    "gear.brand": "Marke",
    "gear.type": "Kategorie",
    "gear.types": "Kategorien",
    "gear.no_type": "Ohne Kategorie",
    "gear.tags": "Tags",
    "gear.tags_hint": "Tags sind frei wählbare Stichworte wie „Winter“ oder „Verleihbar“.",
    "gear.new_tag": "Neuer Tag",
    "gear.new_type": "Neue Kategorie",
    "gear.color_hex": "Farbe (#RRGGBB)",
    "gear.type_standard": "Standard",
    "gear.type_own": "eigene",
    "gear.weight": "Gewicht (g)",
    "gear.status": "Status",
    "gear.status.active": "In Gebrauch",
    "gear.status.retired": "Ausgemustert",
    "gear.price": "Kaufpreis",
    "gear.price_hint": "Höchstens zwei Nachkommastellen; mit Preis ist die Währung Pflicht.",
    "gear.currency": "Währung",
    "gear.purchase_date": "Kaufdatum",
    "gear.description": "Beschreibung",
    "gear.notes": "Notizen",
    "gear.website": "Website",
    "gear.serial_number": "Seriennummer",
    "gear.size": "Größe",
    "gear.color": "Farbe",
    "gear.image": "Bild",
    "gear.image_upload": "Bild hochladen",
    "gear.image_remove": "Bild entfernen",
    "gear.propose": "Im Katalog teilen",
    "gear.propose_hint": "Geteilt werden nur Produktdaten, keine persönlichen Angaben.",
    "gear.proposed": "Vorschlag eingereicht. Geteilt werden nur Produktdaten.",
    "gear.group_by": "Gruppieren nach",
    "gear.group.none": "Gesamt",
    "gear.group.type": "Kategorie",
    "gear.group.tag": "Tag",
    "gear.group.status": "Status",
    "gear.group.brand": "Marke",
    "gear.unassigned": "Nicht zugeordnet",
    "gear.item_count": "{count} Gegenstände",
    "gear.total_weight": "Gesamtgewicht",
    "gear.total_value": "Kaufwert",
    "gear.without_weight": "{count} ohne Gewicht.",
    "gear.without_price": "{count} ohne Preis.",
    "gear.tag_group_hint": (
        "Ein Gegenstand zählt in jedem seiner Tags; die Gruppen können zusammen mehr ergeben "
        "als die Gesamtsumme."
    ),
    "catalog.mine": "Meine Vorschläge",
    "catalog.pending_list": "Offene Vorschläge",
    "catalog.none": "Keine Vorschläge.",
    "catalog.approve": "Freigeben",
    "catalog.reject": "Ablehnen",
    "catalog.status.pending": "Offen",
    "catalog.status.approved": "Freigegeben",
    "catalog.status.rejected": "Abgelehnt",
    "catalog.status.catalog_pending": "Offen",
    "catalog.status.catalog": "Freigegeben",
    "catalog.status.catalog_rejected": "Abgelehnt",
    # --- food ---
    "food.new": "Neues Lebensmittel",
    "food.edit": "Lebensmittel bearbeiten",
    "food.empty": "Keine Lebensmittel gefunden.",
    "food.search_hint": "Name oder Marke",
    "food.with_catalog": "auch im gemeinsamen Katalog",
    "food.barcode": "Barcode",
    "food.barcode_hint": "8, 12, 13 oder 14 Ziffern",
    "food.barcode_invalid": "Ein Barcode hat 8, 12, 13 oder 14 Ziffern.",
    "food.lookup": "Nachschlagen",
    "food.kcal": "Kalorien (kcal je 100 g)",
    "food.kcal_value": "{value} kcal/100 g",
    "food.per_100g": "Nährwerte in Gramm je 100 g",
    "food.protein": "Eiweiß",
    "food.fat": "Fett",
    "food.carbs": "Kohlenhydrate",
    "food.sugar": "davon Zucker",
    "food.salt": "Salz",
    "food.serving": "Portionsgröße (g)",
    "food.proposed": "Vorschlag eingereicht.",
    "food.copy": "Als eigenes Lebensmittel übernehmen",
    "food.copy_hint": "Die Kopie gehört dir und lässt sich danach korrigieren.",
    "food.copy_needs_kcal": "Ohne Kalorienangabe lässt sich der Eintrag nicht übernehmen.",
    "food.copied": "Übernommen. Die Angaben lassen sich jetzt anpassen.",
    "food.source_off": "Quelle:",
    "food.off_note": "Mit „OFF“ markierte Angaben stammen von",
    "catalog.status.private": "Privat",
    # --- tours ---
    "tour.new": "Neue Tour",
    "tour.empty": "Keine Touren gefunden.",
    "tour.search_hint": "Titel oder Beschreibung",
    "tour.scope.all": "Alle",
    "tour.scope.mine": "Meine",
    "tour.scope.shared": "Mit mir geteilt",
    "tour.title": "Titel",
    "tour.summary": "Beschreibung",
    "tour.create": "Tour anlegen",
    "tour.create_hint": "Track, Fotos und Listen kommen im nächsten Schritt dazu.",
    "tour.by": "von {name}",
    "tour.permission.edit": "Bearbeiten erlaubt",
    "tour.permission.read": "Nur lesen",
    "tour.history": "Verlauf",
    "tour.sharing": "Teilen",
    "tour.export": "Export (JSON)",
    "tour.leave": "Aus meiner Liste entfernen",
    "tour.contacts": "Kontakte",
    "tour.facts": "Eckdaten",
    "tour.start": "Start",
    "tour.end": "Ende",
    "tour.duration": "Dauer",
    "tour.moving_time": "Zeit in Bewegung",
    "tour.distance": "Strecke",
    "tour.ascent": "Aufstieg",
    "tour.descent": "Abstieg",
    "tour.highest": "Höchster Punkt",
    "tour.lowest": "Tiefster Punkt",
    "tour.pack_weight": "Rucksackgewicht am Start",
    "tour.calories_eaten": "Gegessen",
    "tour.calories_burned": "Verbrauch",
    "tour.estimated": "geschätzt",
    "tour.estimate_method.heart_rate": "Schätzung aus der Herzfrequenz (Keytel et al. 2005).",
    "tour.estimate_method.acsm_walking": "Schätzung aus Strecke, Steigung und Gewicht (ACSM).",
    "tour.estimate_reason.no_profile": "Für eine Schätzung fehlt das Gewicht im Profil.",
    "tour.estimate_reason.no_track": "Für eine Schätzung fehlt ein Track.",
    "tour.estimate_reason.no_duration": "Für eine Schätzung fehlt die Dauer.",
    "tour.use_estimate": "Schätzung statt eigener Angabe verwenden",
    "tour.kcal": "{value} kcal",
    "tour.heart_rate": "Herzfrequenz",
    "tour.heart_rate_value": "Ø {avg}, max. {max} Schläge/min",
    "tour.health_note": "Nur für dich sichtbar.",
    "tour.track": "Track",
    "tour.track_source.device": "aufgezeichnet",
    "tour.track_source.drawn": "gezeichnet",
    "tour.no_track": "Noch kein Track.",
    "tour.gpx_file": "GPX-Datei",
    "tour.gpx_upload": "GPX hochladen",
    "tour.gpx_replace_hint": "Eine neue Datei ersetzt den bisherigen Track.",
    "tour.gpx_uploaded": "Track ausgewertet.",
    "tour.gpx_download": "GPX herunterladen",
    "tour.track_remove": "Track entfernen",
    "tour.profile": "Höhenprofil",
    "tour.course": "Verlauf der Tour",
    "tour.places_detect": "Gipfel und Pässe neu suchen",
    "tour.places_done": "Orte entlang des Tracks aktualisiert.",
    "tour.station.start": "Start",
    "tour.station.end": "Ende",
    "tour.station.peak": "Gipfel",
    "tour.station.saddle": "Pass / Sattel",
    "tour.station.high_point": "Höchster Punkt",
    "tour.station.waypoint": "Wegpunkt",
    "tour.station.custom": "Wegpunkt",
    "tour.station.photo": "Foto",
    "tour.place": "Ort",
    "tour.elevation": "Höhe",
    "tour.at_distance": "Bei",
    "tour.time": "Zeit",
    "tour.photos": "Fotos",
    "tour.photos_upload": "Fotos hochladen",
    "tour.photos_uploaded": "{count} Fotos hochgeladen.",
    "tour.photo_caption": "Bildunterschrift",
    "tour.photo_cover": "Als Titelbild",
    "tour.photo_is_cover": "Titelbild",
    "tour.photo_offset": "Zeitversatz der Kamera (Minuten)",
    "tour.photo_offset_hint": "Wird zur Aufnahmezeit addiert, z. B. -120 für eine Kamera auf MESZ.",
    "tour.photo_offset_apply": "Anwenden",
    "tour.photo_position.exif_gps": "Position aus dem Foto",
    "tour.photo_position.exif_time": "Position über die Aufnahmezeit",
    "tour.photo_position.manual": "Position von Hand",
    "tour.photo_position.none": "ohne Position",
    "tour.waypoints_from_photos": "Wegpunkte aus Fotos anlegen",
    "tour.weather": "Wetter",
    "tour.weather_fetch": "Wetter neu abrufen",
    "tour.weather_outdated": "Ort oder Zeit haben sich seit dem Abruf geändert.",
    "tour.weather_point.start": "Start",
    "tour.weather_point.summit": "Höchster Punkt",
    "tour.weather_point.end": "Ende",
    "tour.weather_point.manual": "Eigener Punkt",
    "tour.weather_temperature": "Temperatur",
    "tour.weather_wind": "Wind (Böen)",
    "tour.weather_precipitation": "Niederschlag",
    "tour.weather_clouds": "Bewölkung",
    "tour.weather_freezing": "Nullgradgrenze",
    "tour.weather_source": "Wetterdaten: Open-Meteo",
    "tour.gear": "Ausrüstung",
    "tour.food": "Essen",
    "tour.peaks": "Gipfel",
    "tour.partners": "Mit dabei",
    "tour.quantity": "Anzahl",
    "tour.carried": "getragen",
    "tour.eaten": "gegessen",
    "tour.amount": "Menge (g)",
    "tour.remove": "entfernen",
    "tour.add_gear": "Gegenstand hinzufügen",
    "tour.add_list": "Packliste übernehmen",
    "tour.add_list_hint": "Fügt alle Gegenstände der Liste hinzu, die noch nicht in der Tour sind.",
    "tour.add_food": "Lebensmittel hinzufügen",
    "tour.add_peak": "Gipfel hinzufügen",
    "tour.choose": "– auswählen –",
    "tour.snapshot_hint": (
        "Gewicht und Kalorien werden beim Hinzufügen festgehalten; spätere Änderungen an "
        "Ausrüstung oder Lebensmitteln ändern die Tour nicht."
    ),
    "tour.no_contacts": "Noch keine Kontakte.",
    "tour.manage_contacts": "Kontakte verwalten",
    "tour.owner_only_hint": "Zeiten und Zahlenwerte kann nur der Besitzer der Tour ändern.",
    "tour.manual_values": "Eigene Angaben (leer = berechnet)",
    "tour.duration_minutes": "Dauer (Minuten)",
    "tour.pack_weight_g": "Rucksackgewicht (g)",
    "tour.calories_burned_manual": "Kalorienverbrauch (kcal)",
    "tour.start_time": "Beginn",
    "tour.end_time": "Ende",
    "tour.time_follows_track": "Mit einem aufgezeichneten Track folgen die Zeiten dem Track.",
    "tour.save_and_stay": "Speichern und weiter bearbeiten",
    "tour.conflict": (
        "Die Tour wurde inzwischen geändert. Felder, die du nicht angefasst hast, zeigen den "
        "neuen Stand; deine Änderungen sind eingetragen. Erneutes Speichern übernimmt sie."
    ),
    "tour.conflict_title": "Abweichungen",
    "tour.conflict_none": "Deine Änderungen berühren keine Felder, die inzwischen geändert wurden.",
    "tour.conflict_field": "Feld",
    "tour.conflict_current": "Neuer Stand",
    "tour.conflict_mine": "Deine Eingabe",
    "tour.conflict_lists": (
        "Die Listen unten zeigen den neuen Stand; deine Änderungen an vorhandenen Zeilen "
        "sind eingetragen. Entfernte oder neu gewählte Einträge bitte prüfen."
    ),
    "tour.discard": "Eigene Eingaben verwerfen",
    "tour.public_note": "Öffentlich geteilte Tour",
    "tour.approximate": "ungefähr",
    # --- editing on the map ---
    "map.title": "Auf der Karte bearbeiten",
    "map.intro": (
        "Positionen lassen sich eintippen oder mit „Auf der Karte wählen“ per Klick in die "
        "Karte übernehmen."
    ),
    "map.lat": "Breite",
    "map.lon": "Länge",
    "map.pick": "Auf der Karte wählen",
    "map.pick_hint": "Jetzt in die Karte klicken, um die Position zu übernehmen.",
    "map.waypoints": "Wegpunkte",
    "map.waypoint_new": "Neuer Wegpunkt",
    "map.photo_positions": "Position der Fotos",
    "map.photo_hint": "Eine von Hand gesetzte Position bleibt, bis du wieder „automatisch“ wählst.",
    "map.photo_auto": "Wieder automatisch",
    "map.points": "Start und Ende",
    "map.points_from_track": (
        "Start und Ende folgen dem aufgezeichneten Track; nur die Namen lassen sich ändern."
    ),
    "map.draw": "Track zeichnen",
    "map.draw_intro": (
        "Für Touren ohne Aufzeichnung: Punkte der Reihe nach in die Karte klicken. "
        "Die Höhen ergänzt der Server."
    ),
    "map.draw_replaces": "Der gezeichnete Track ersetzt den vorhandenen Track.",
    "map.draw_points": "Punkte (je Zeile: Breite, Länge)",
    "map.draw_start": "In der Karte zeichnen",
    "map.draw_hint": "Jeder Klick in die Karte setzt den nächsten Punkt des Tracks.",
    "map.draw_undo": "Letzten Punkt entfernen",
    "map.draw_save": "Track speichern",
    "map.weather_point": "Wetter für einen eigenen Punkt",
    # --- history ---
    "history.title": "Verlauf",
    "history.version": "Version {version}",
    "history.kind.created": "angelegt",
    "history.kind.updated": "geändert",
    "history.kind.restored": "wiederhergestellt",
    "history.kind.deleted": "gelöscht",
    "history.unknown_author": "gelöschter Nutzer",
    "history.restore": "Diesen Stand wiederherstellen",
    "history.restore_hint": "Der Verlauf bleibt erhalten; es entsteht eine neue Version.",
    "history.restored": "Stand von Version {version} wiederhergestellt.",
    "history.changes": "Änderungen gegenüber der Version davor",
    "history.no_changes": "Keine Unterschiede.",
    "history.added": "hinzugefügt",
    "history.removed": "entfernt",
    "history.changed": "geändert",
    "history.reordered": "Reihenfolge geändert",
    "history.current": "aktuell",
    "field.title": "Titel",
    "field.summary": "Beschreibung",
    "field.start_time": "Beginn",
    "field.end_time": "Ende",
    "field.duration_minutes": "Dauer (Minuten)",
    "field.pack_weight_start_g": "Rucksackgewicht (g)",
    "field.calories_burned": "Kalorienverbrauch (kcal)",
    "field.calories_burned_source": "Quelle des Kalorienverbrauchs",
    "field.gear": "Ausrüstung",
    "field.food": "Essen",
    "field.peaks": "Gipfel",
    "field.waypoints": "Wegpunkte",
    "field.partners": "Mit dabei",
    "field.photos": "Fotos",
    "field.cover_photo_id": "Titelbild",
    "field.photo_time_offset_seconds": "Zeitversatz der Kamera (Sekunden)",
    "field.track_source": "Track",
    "field.gpx_file_id": "GPX-Datei",
    "field.points_source": "Herkunft von Start und Ende",
    "field.start_name": "Name des Starts",
    "field.end_name": "Name des Endes",
    "field.start_lat": "Start (Breite)",
    "field.start_lon": "Start (Länge)",
    "field.end_lat": "Ende (Breite)",
    "field.end_lon": "Ende (Länge)",
    "field.quantity": "Anzahl",
    "field.carried": "getragen",
    "field.eaten": "gegessen",
    "field.amount_g": "Menge (g)",
    "field.name": "Name",
    "field.elevation_m": "Höhe (m)",
    "field.caption": "Bildunterschrift",
    "value.true": "ja",
    "value.false": "nein",
    "value.none": "–",
    # --- sharing ---
    "share.title": "Teilen",
    "share.users": "Mit Nutzern teilen",
    "share.none": "Noch mit niemandem geteilt.",
    "share.email": "E-Mail-Adresse des Nutzers",
    "share.permission": "Recht",
    "share.permission.read": "Lesen",
    "share.permission.edit": "Bearbeiten",
    "share.edit_hint": (
        "Mit „Bearbeiten“ lassen sich Texte, Listen und Fotos ändern – nicht aber Track, "
        "Zeiten, Zahlenwerte und Freigaben."
    ),
    "share.add": "Teilen",
    "share.added": "Mit {name} geteilt.",
    "share.change": "Ändern",
    "share.remove": "Freigabe entfernen",
    "share.health_note": "Herzfrequenz und Profildaten sehen andere Nutzer nie.",
    "link.title": "Öffentliche Links",
    "link.intro": "Wer den Link kennt, kann die Tour ohne Anmeldung ansehen.",
    "link.none": "Noch kein Link.",
    "link.create": "Link erstellen",
    "link.expires": "Gültig bis (leer = unbegrenzt)",
    "link.expires_at": "gültig bis {date}",
    "link.hide_start": "Start und Ende nur ungefähr zeigen (etwa 1 km)",
    "link.strip_gps": "Position aus Fotos entfernen",
    "link.health": "Kalorienverbrauch und Herzfrequenz zeigen",
    "link.revoke": "Widerrufen",
    "link.revoked": "widerrufen",
    "link.expired": "abgelaufen",
    "link.active": "aktiv",
    "contact.title": "Kontakte",
    "contact.intro": (
        "Kontakte sind die Personen, die du als Tourenpartner eintragen kannst. "
        "Mit einer E-Mail-Adresse wird der Kontakt mit einem Nutzer verknüpft."
    ),
    "contact.name": "Name",
    "contact.email": "E-Mail des Nutzers (optional)",
    "contact.linked": "Nutzer: {name}",
    # --- errors ---
    "error.network": "Der Server ist gerade nicht erreichbar. Bitte später erneut versuchen.",
    "error.validation": "Die Eingaben wurden nicht angenommen. Bitte prüfen.",
    "error.invalid_credentials": "E-Mail oder Passwort ist falsch.",
    "error.email_taken": "Diese E-Mail-Adresse ist schon registriert.",
    "error.registration_closed": "Auf diesem Server können keine neuen Konten angelegt werden.",
    "error.rate_limited": "Zu viele Versuche. Bitte kurz warten.",
    "error.session_expired": "Die Anmeldung ist abgelaufen. Bitte neu anmelden.",
    "error.forbidden": "Dafür fehlt die Berechtigung.",
    "error.not_found": "Nicht gefunden.",
    "error.conflict": "Das gibt es schon.",
    "error.too_large": "Die Datei ist zu groß.",
    "error.csrf": "Das Formular ist abgelaufen. Bitte die Seite neu laden und erneut absenden.",
    "error.unknown": "Etwas ist schiefgegangen. Bitte später erneut versuchen.",
    "error.invalid_image": "Die Datei ist kein unterstütztes Bild (JPEG, PNG, WebP).",
    "error.invalid_gpx": "Die Datei ist keine lesbare GPX-Datei.",
    "error.owner_only_field": "Zeiten und Zahlenwerte kann nur der Besitzer der Tour ändern.",
    "error.insufficient_permission": "Dafür fehlt die Berechtigung.",
    "error.already_in_catalog": "Dieser Eintrag ist schon mit einem Katalogeintrag verknüpft.",
    "error.barcode_in_catalog": "Im Katalog gibt es schon ein Produkt mit diesem Barcode.",
    "error.source_unavailable": "Der externe Dienst ist gerade nicht erreichbar.",
    "error.product_not_found": "Zu diesem Barcode gibt es noch keinen Eintrag.",
    "error.points_from_track": "Start und Ende folgen dem Track.",
    "error.no_sample_points": "Die Tour braucht erst Start oder Ende mit einer Zeit.",
    "error.no_profile": "Für eine Schätzung fehlt das Gewicht im Profil.",
    "error.no_track": "Für eine Schätzung fehlt ein Track.",
    "error.no_duration": "Für eine Schätzung fehlt die Dauer.",
    "error.unknown_user": "Kein Nutzer mit dieser E-Mail-Adresse.",
    "error.already_shared": "Die Tour ist mit diesem Nutzer schon geteilt.",
    "error.share_with_owner": "Die Tour gehört diesem Nutzer bereits.",
    "error.version_conflict": "Die Tour wurde inzwischen geändert. Bitte die Seite neu laden.",
    "error.page_404": "Diese Seite gibt es nicht.",
}


def label(key: str) -> str:
    """Name of a field of the tour for the history; the key itself if it has none."""
    return TEXTS.get(f"field.{key}", key)


def t(key: str, **values) -> str:
    """The German text for a key; the key itself if a text is missing."""
    text = TEXTS.get(key, key)
    return text.format(**values) if values else text
