"""All texts of the web frontend, in German. Templates and views use `t('key')`."""

TEXTS = {
    "app.title": "hiker",
    "nav.tours": "Touren",
    "nav.gear": "Ausrüstung",
    "nav.food": "Essen",
    "nav.profile": "Profil",
    "nav.logout": "Abmelden",
    "action.save": "Speichern",
    "action.delete": "Löschen",
    "action.edit": "Bearbeiten",
    "action.cancel": "Abbrechen",
    "action.search": "Suchen",
    "action.add": "Hinzufügen",
    "action.back": "Zurück",
    "common.all": "Alle",
    "common.none": "Keine",
    "common.name": "Name",
    "common.saved": "Gespeichert.",
    "common.deleted": "Gelöscht.",
    "common.confirm_delete": "Wirklich löschen?",
    # --- auth ---
    "auth.login": "Anmelden",
    "auth.register": "Konto anlegen",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.password_hint": "Mindestens 10 Zeichen",
    "auth.display_name": "Anzeigename",
    "auth.to_register": "Noch kein Konto? Konto anlegen",
    "auth.to_login": "Schon ein Konto? Anmelden",
    "auth.signed_in_as": "Angemeldet als {name}",
    "auth.admin": "Administrator",
    "profile.title": "Profil",
    "profile.intro": (
        "Diese Angaben sind freiwillig. Sie dienen nur der Schätzung des Kalorienverbrauchs "
        "und sind für niemanden sonst sichtbar."
    ),
    "profile.weight": "Gewicht (kg)",
    "profile.birth_year": "Geburtsjahr",
    "profile.sex": "Geschlecht",
    "profile.sex.none": "nicht festgelegt",
    "profile.sex.female": "weiblich",
    "profile.sex.male": "männlich",
    "profile.sex.trans": "trans",
    "profile.sex.undisclosed": "keine Angabe",
    "profile.max_heart_rate": "Maximale Herzfrequenz",
    "profile.resting_heart_rate": "Ruheherzfrequenz",
    # --- gear ---
    "gear.new": "Neuer Gegenstand",
    "gear.edit": "Gegenstand bearbeiten",
    "gear.empty": "Keine Ausrüstung gefunden.",
    "gear.search_hint": "Name oder Marke",
    "gear.summary": "Summen",
    "gear.manage": "Tags und Kategorien",
    "gear.catalog": "Katalog",
    "gear.brand": "Marke",
    "gear.type": "Kategorie",
    "gear.types": "Kategorien",
    "gear.no_type": "Ohne Kategorie",
    "gear.tags": "Tags",
    "gear.tags_hint": "Tags sind frei wählbare Stichworte wie „Winter“ oder „Verleihbar“.",
    "gear.new_tag": "Neuer Tag",
    "gear.new_type": "Neue Kategorie",
    "gear.color_hex": "Farbe (#RRGGBB)",
    "gear.type_standard": "Standard",
    "gear.type_own": "eigene",
    "gear.weight": "Gewicht (g)",
    "gear.status": "Status",
    "gear.status.active": "In Gebrauch",
    "gear.status.retired": "Ausgemustert",
    "gear.price": "Kaufpreis",
    "gear.price_hint": "Höchstens zwei Nachkommastellen; mit Preis ist die Währung Pflicht.",
    "gear.currency": "Währung",
    "gear.purchase_date": "Kaufdatum",
    "gear.description": "Beschreibung",
    "gear.notes": "Notizen",
    "gear.website": "Website",
    "gear.serial_number": "Seriennummer",
    "gear.size": "Größe",
    "gear.color": "Farbe",
    "gear.image": "Bild",
    "gear.image_upload": "Bild hochladen",
    "gear.image_remove": "Bild entfernen",
    "gear.propose": "Im Katalog teilen",
    "gear.propose_hint": "Geteilt werden nur Produktdaten, keine persönlichen Angaben.",
    "gear.proposed": "Vorschlag eingereicht. Geteilt werden nur Produktdaten.",
    "gear.group_by": "Gruppieren nach",
    "gear.group.none": "Gesamt",
    "gear.group.type": "Kategorie",
    "gear.group.tag": "Tag",
    "gear.group.status": "Status",
    "gear.group.brand": "Marke",
    "gear.unassigned": "Nicht zugeordnet",
    "gear.item_count": "{count} Gegenstände",
    "gear.total_weight": "Gesamtgewicht",
    "gear.total_value": "Kaufwert",
    "gear.without_weight": "{count} ohne Gewicht.",
    "gear.without_price": "{count} ohne Preis.",
    "gear.tag_group_hint": (
        "Ein Gegenstand zählt in jedem seiner Tags; die Gruppen können zusammen mehr ergeben "
        "als die Gesamtsumme."
    ),
    "catalog.mine": "Meine Vorschläge",
    "catalog.pending_list": "Offene Vorschläge",
    "catalog.none": "Keine Vorschläge.",
    "catalog.approve": "Freigeben",
    "catalog.reject": "Ablehnen",
    "catalog.status.pending": "Offen",
    "catalog.status.approved": "Freigegeben",
    "catalog.status.rejected": "Abgelehnt",
    "catalog.status.catalog_pending": "Offen",
    "catalog.status.catalog": "Freigegeben",
    "catalog.status.catalog_rejected": "Abgelehnt",
    # --- errors ---
    "error.network": "Der Server ist gerade nicht erreichbar. Bitte später erneut versuchen.",
    "error.validation": "Die Eingaben wurden nicht angenommen. Bitte prüfen.",
    "error.invalid_credentials": "E-Mail oder Passwort ist falsch.",
    "error.email_taken": "Diese E-Mail-Adresse ist schon registriert.",
    "error.registration_closed": "Auf diesem Server können keine neuen Konten angelegt werden.",
    "error.rate_limited": "Zu viele Versuche. Bitte kurz warten.",
    "error.session_expired": "Die Anmeldung ist abgelaufen. Bitte neu anmelden.",
    "error.forbidden": "Dafür fehlt die Berechtigung.",
    "error.not_found": "Nicht gefunden.",
    "error.conflict": "Das gibt es schon.",
    "error.too_large": "Die Datei ist zu groß.",
    "error.csrf": "Das Formular ist abgelaufen. Bitte die Seite neu laden und erneut absenden.",
    "error.unknown": "Etwas ist schiefgegangen. Bitte später erneut versuchen.",
    "error.invalid_image": "Die Datei ist kein unterstütztes Bild (JPEG, PNG, WebP).",
    "error.invalid_gpx": "Die Datei ist keine lesbare GPX-Datei.",
    "error.owner_only_field": "Zeiten und Zahlenwerte kann nur der Besitzer der Tour ändern.",
    "error.insufficient_permission": "Dafür fehlt die Berechtigung.",
    "error.already_in_catalog": "Dieser Eintrag ist schon mit einem Katalogeintrag verknüpft.",
    "error.barcode_in_catalog": "Im Katalog gibt es schon ein Produkt mit diesem Barcode.",
    "error.source_unavailable": "Der externe Dienst ist gerade nicht erreichbar.",
    "error.product_not_found": "Zu diesem Barcode gibt es noch keinen Eintrag.",
    "error.points_from_track": "Start und Ende folgen dem Track.",
    "error.no_sample_points": "Die Tour braucht erst Start oder Ende mit einer Zeit.",
    "error.no_profile": "Für eine Schätzung fehlt das Gewicht im Profil.",
    "error.no_track": "Für eine Schätzung fehlt ein Track.",
    "error.no_duration": "Für eine Schätzung fehlt die Dauer.",
    "error.unknown_user": "Kein Nutzer mit dieser E-Mail-Adresse.",
    "error.already_shared": "Die Tour ist mit diesem Nutzer schon geteilt.",
    "error.share_with_owner": "Die Tour gehört diesem Nutzer bereits.",
    "error.page_404": "Diese Seite gibt es nicht.",
}


def t(key: str, **values) -> str:
    """The German text for a key; the key itself if a text is missing."""
    text = TEXTS.get(key, key)
    return text.format(**values) if values else text
